[build-system] 
requires = [ "setuptools",] 
build-backend = "setuptools.build_meta" 

[project] 
name = "$src-template" 
version = "0.0.0a0" 
dependencies = [ "importlib-resources; python_version<\"3.10\"",] 

