[build-system] 
requires = [ "setuptools",] 
build-backend = "setuptools.build_meta" 

[project] 
name = "cfs_zippy" 
version = "1.0.1" 
dependencies = [ "importlib-resources; python_version<\"3.10\"",] 

